spring.application.name=friendsAgenda

# Conexión a MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/friends_agenda
spring.datasource.username=friends_agenda
spring.datasource.password=passfriendsagenda
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true

# Zona horaria recomendada (evita problemas con DATE/TIMESTAMP)
spring.jpa.properties.hibernate.jdbc.time_zone=America/Bogota
